spring.datasource.url=jdbc:mysql://mysql.railway.internal:3306/railway
spring.datasource.username=root
spring.datasource.password=UGZZgeeAFTYFEKfgqqiSkkSXrjdWLZuZ
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=e54d0fd324711b512854a26664bae725d17447661981449c2d26eff71707d7a608563d0b891a368f8eec1cdaea1cb43357b422fb72d597e24e46b3de72fdef64
app.client.url=https://unique-shortbread-0aab4d.netlify.app

server.port=8080