spring.datasource.url=jdbc:mysql://boye7sttt35f7iacsqpr-mysql.services.clever-cloud.com:3306/boye7sttt35f7iacsqpr
spring.datasource.username=ulg2h02drwlx6gt3
spring.datasource.password=EuhMSVwT657u9RC8svGQ
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=e54d0fd324711b512854a26664bae725d17447661981449c2d26eff71707d7a608563d0b891a368f8eec1cdaea1cb43357b422fb72d597e24e46b3de72fdef64
app.client.url=http://localhost:4200

server.port=8080